rm(list=ls())
#install.packages("forecast")
#install.packages("tseries")
library(forecast)
library(tseries)
setwd("F:/6th Sem/CSE3506 - Essentials of Data Analytics/Lab/Datasets")
sales <- read.csv("sales1.csv")
colnames(sales)
sales_ts <- ts(sales$Sales.INR, start = c(2015), frequency = 12)
autoplot(sales_ts)
adf.test(sales_ts, k=12)
sales_ts_d1 <- diff(sales_ts, difference=1)
adf.test(sales_ts_d1, k=12)
sales_ts_d1 <- diff(sales_ts, difference=2)
adf.test(sales_ts_d1, k=12)
autoplot(sales_ts_d1)
#tsmod <- Arima(y=sales_ts, order = c(p,d,q))
pacf(sales_ts_d1)
acf(sales_ts_d1)
autoplot(sales_ts_d1)
tsmod <- Arima(y=sales_ts, order = c(4,2,6))
tsmod
forecast(tsmod, h=12)
autoplot(forecast(tsmod, h=12))